#训练核心参数
training:
  total_timesteps: 100000        #每次运行'learn'的总步数
  model_name: "model"            #模型的统一名称，用于持续学习
  models_dir: "models"           #保存模型的目录
  logs_dir: "logs"               #保存日志的目录
  device: "cpu"                  #训练设备: "cpu" 或 "cuda" 或 "auto"
  learning_rate: 0.0003          #PPO学习率的初始值

#环境相关参数
environment:
  max_steps: 3000                #每个回合的最大步数上限
  reset_offset: [-5, 5]          #新回合目标点的随机偏移范围 [min, max]

#奖励函数超参数
reward:
  target_reached_threshold: 1.0  #判定成功的距离
  reach_target_reward: 20.0      #成功到达的奖励
  truncated_penalty: -5.0        #超时失败的惩罚
  alive_penalty: -0.1            #每一步的生存惩罚
  w_distance: 1.0                #距离奖励的权重
  w_angle: 0.5                   #朝向奖励的权重

#服务器与通信参数
server:
  mc_port: 25565
  mc_version: "1.21"
  ws_port: 3000
  viewer_port: 3030